public class ViewResponsesExCon {
    /*public Unit__c unit{get;set;}
    public List<Response__c> responseObj{get;set;}
    
    public ViewResponsesExCon(ApexPages.StandardController stdCont){
        unit = (Unit__c)stdCont.getRecord();
        responseObj = [Select 	Id,Unit_of_Interest__c,Unit_of_Interest__r.Unit_of_Interest_ID__c,Unit_of_Interest__r.Unit_of_Interest_Description__c,Unit_of_Interest__r.Name,Unit_of_Interest__r.Enterprise__c,
                       			Unit_of_Interest__r.Group_Top_Enterprise__c,Collection_Instance__c,Collection_Instance__r.Name,Instrument__r.Name,Collection_Mode__c,Key__c,Contact__r.FirstName,Contact__r.LastName,Status__c,
                       			Extension_Date__c,CreatedDate  
                       from 	Response__c 
                       where 	(Unit_of_Interest__r.Enterprise__c = :unit.Id or Unit_of_Interest__c = :unit.Id or Unit_of_Interest__r.Group_Top_Enterprise__c = :unit.Id)];
    }*/
}